import Headers from '@/components/Headers';
import './globals.css';
import { Poppins } from 'next/font/google';
import Welcome from '@/components/Welcome';
import Footer from '@/components/Footer';

const poppins = Poppins({ weight: '400', subsets: ['devanagari'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={poppins.className}>
        <Headers />
        <Welcome />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
